//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionCard : FollowerCard
    {
        public int LevelUpCardID { get; set; }
        public int SpellCardID { get; set; }
        public string LevelUpConditions { get; set; }
    
        public virtual FullCard FullCard { get; set; }
        public virtual FullCard FullCard1 { get; set; }
    }
}
