//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowerCard : FullCard
    {
        public Nullable<int> AttackRating { get; set; }
        public Nullable<int> HealthRating { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
    }
}
