//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FullCard()
        {
            this.ChampionCards = new HashSet<ChampionCard>();
            this.ChampionCards1 = new HashSet<ChampionCard>();
        }
    
        public int ID { get; set; }
        public string CardName { get; set; }
        public string Region { get; set; }
        public Nullable<int> ManaCost { get; set; }
        public string CardType { get; set; }
        public string CardRarity { get; set; }
        public string CardDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChampionCard> ChampionCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChampionCard> ChampionCards1 { get; set; }
    }
}
